package com.alancamargo.weapons.di

const val DB_WEAPON_MAPPER = "DB_WEAPON_MAPPER"
const val DB_CALIBRE_MAPPER = "DB_CALIBRE_MAPPER"
const val DB_COUNTRY_MAPPER = "DB_COUNTRY_MAPPER"
const val DB_MANUFACTURER_MAPPER = "DB_MANUFACTURER_MAPPER"
const val DB_YEAR_MAPPER = "DB_YEAR_MAPPER"
const val DB_WEAPON_TYPE_MAPPER = "DB_WEAPON_TYPE_MAPPER"